# name: Deployment
# on:
#   push:
#     branches:
#       - main
#       - testing

# jobs:
#   test:
#     runs-on: ubuntu-latest
#     container:
#       image: node:16
#     environment: ${{ vars.envi }}
#     env:
#       MONGODB_CLUSTER_ADDRESS: ${{ secrets.MONGODB_CLUSTER_ADDRESS }}
#       MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }}
#       MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
#       PORT: ${{ secrets.PORT }}
    
#     steps:
#       - name: Get Code
#         uses: actions/checkout@v3
#       - name: Cache dependencies
#         uses: actions/cache@v3
#         with:
#           path: ~/.npm
#           key: npm-deps-${{ hashFiles('**/package-lock.json') }}
#       - name: Install dependencies
#         run: npm ci
#       - name: Run server
#         run: npm start & npx wait-on http://127.0.0.1:$PORT
#       - name: Run tests
#         run: npm test
#       - name: Output information
#         run: echo "${{ vars.MONGODB_USERNAME }}"
        
#   deploy:
#     needs: test
#     runs-on: ubuntu-latest
#     container:
#       image: node:16
#     environment: ${{ vars.envi }}
#     env:
#       MONGODB_CLUSTER_ADDRESS: ${{ secrets.MONGODB_CLUSTER_ADDRESS }}
#       MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }}
#       MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
#       PORT: ${{ secrets.PORT }}
#     steps:
#       - name: Output information
#         run: |        
#           echo "${{ secrets.MONGODB_USERNAME }}"






name: Deployment
on:
  push:
    branches:
      - main
      - testing

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:16

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example

    env:
      MONGODB_CLUSTER_ADDRESS: mongodb
      MONGODB_USERNAME: root
      MONGODB_PASSWORD: example
      PORT: 27017

    steps:
      - name: Get Code
        uses: actions/checkout@v3
      
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-deps-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci

      - name: Download wait-for-it.sh
        run: wget https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh
        shell: bash

      - name: Make wait-for-it.sh executable
        run: chmod +x wait-for-it.sh
        shell: bash

      - name: Wait for MongoDB to be ready
        run: ./wait-for-it.sh mongodb:27017 --timeout=60 --strict -- echo "MongoDB is up"
        shell: bash

      - name: Run server
        run: npm start & npx wait-on http://127.0.0.1:${{ secrets.PORT }}
        shell: bash

      - name: Run tests
        run: npm test

      - name: Output information
        run: echo "${{ vars.MONGODB_USERNAME }}"

  deploy:
    needs: test
    runs-on: ubuntu-latest
    container:
      image: node:16

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example

    env:
      MONGODB_CLUSTER_ADDRESS: mongodb
      MONGODB_USERNAME: root
      MONGODB_PASSWORD: example
      PORT: ${{ secrets.PORT }}  # Use the port from secrets

    steps:
      - name: Output information
        run: |
          echo "${{ secrets.MONGODB_USERNAME }}"
